### ISSUE TITLE
Fixes and improvements for MVP 0.1

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#197]
This task is about reviewing some detected issues as well as making some improvements in our mvp:

- **Improve search**
  - use a single search context so we don't have to pass states and callbacks around and we centralize everything that matters in a search: query and results
  - fix visual "jumps" each time we update the seach query, try to make results appear smoother.
  - make rows and header fully scrollable so we have more space in a smartphone screen.

- **Move dispatch page into a template:**
  - I read about [atoms, molecules, templates and pages](https://blog.kamathrohan.com/atomic-design-methodology-for-building-design-systems-f912cf714f53) and loved the idea! 
  - The idea is very similiar to the dispatch page but, to convert it into a more reusable template so we can easily use it in chats, games etc. Its main responsibility is to draw data but does not care about how it get it, that should be a responsibility of th page instantiating it.
  - usersPage now holds the responsability of handling data and pass it to templates. The same idea can be easily replicated with other types of rows pages like chats, games, groups etc.

- **Improve UX of editAvatar page and component:**
  -  Make editableAvatar work in touch screens
  -  Add feedback messages to know an action was successful
  - Make selected avatar appear and disabling editing while uploading.

**Comment by Damrod** [comment]
> The idea is very similiar to the dispatch page but, to convert it into a more reusable template so we can easily use it in chats, games etc. Its main responsibility is to draw data but does not care about how it get it, that should be a responsibility of th page instantiating it.

It's not a very similar to the dispatch page. It's literally the idea already in the dispatch page, as it is currently implemented before your changes.
