### ISSUE TITLE
typescript training

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#2]
## Todo

Add list of training exercises from https://exercism.org

**Comment by vdedios** [comment]
🚧 Blocked by https://github.com/42AGV/ft_transcendence/issues/5

**Comment by gbudau** [comment]
## Course suggestion
https://docs.microsoft.com/en-us/learn/paths/build-javascript-applications-typescript/

### why?

- cover all basic typing concepts
- short, can be done in a few days while being relaxed
