### ISSUE TITLE
Improve webapp routing

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#200]
This issue is about fixing and improving some aspects about routing:

- We fetch the auth user in every single navigation:
  - We already know who that user is because is auth (and present in auth context), so the idea would be reusing it (and updating it's state everytime we update it)
- We have a bit weird routes.
  - For example, for a normal user we would navigate to `/users/239482309482390-234o89234o238`. But for the auth user, `/user`
  - A more unified and simpler way to do this would be simply: `/user/<username>` and `/users` to display all.
- We have inconsistencies in auth user page: if navigated from a user row, it displays it like a normal user. But if navigate it from user profile, it displays it like a `isMe` user.
  - We can fix this using a single route for a user as mentioned in previous point.

**Comment by Damrod** [comment]
>We have inconsistencies in auth user page: if navigated from a user row, it displays it like a normal user. But if navigate it from user profile, it displays it like a isMe user.

This is intentional. If it's displayed from inside IsMe , it displays all available information. Otherwise, it displays info as it would be available to others. This exists, for instance, in the 42 intra as well
