### ISSUE TITLE
Redesign Avatar implementation

### ISSUE THREAD

**Issue by fizcamposancos** [42AGV/ft_transcendence#270]
As they are also going to be used by chat and, it could may make sense to create a module

**Comment by Damrod** [comment]
Linked issues #342 , #317

And comment from gbudau [here](https://github.com/42AGV/ft_transcendence/pull/329#discussion_r1021665214)

> Good catch! I've changed the url of the avatar in the ChatPage.
> 
> I think we need a different endpoint for the chatroom avatars because the current endpoint is for the user avatars /api/v1/users/avatars/{avatarId}, or we could create a new controller for the avatars with an endpoint like /api/v1/avatar/{avatarId}
