### ISSUE TITLE
In user page, refactor relationship between one to one message button and block toggle

### ISSUE THREAD

**Issue by Damrod** [42AGV/ft_transcendence#330]
As of now, we have a button to send messages to other users that is available to the authenticated user in any other user's user page, depending on:

1. Whether the authenticated user is blocking the user.
2. Whether the authenticated user is being blocked by the particular user.

This basically makes the user be able to be completely aware of blocks he's the recipient of.

Please, rethink. Possible solutions may include:
1. completely removing the blocking user from the blocked user's user list OR
2. silently not delivering the sent messages from the blocked to the blocker without actually removing access to the one to one chat page OR
3. not do anything, if we all agree this is an acceptable violation of the blocking user's privacy, or if we just decide it's too much bother to change it, since the project is never going to go into production in the real world.

**Comment by Damrod** [comment]
Also, according to the subject:
```
Users must be able to block other user and therefore they will not see their messages
anymore
```
Does this include the messages the blocked user will send in chatrooms where blocker and blockee are both members? Decide.

**Comment by gbudau** [comment]
I vote for 2:
- silently not delivering the sent messages from the blocked to the blocker without actually removing access to the one-to-one chat page

> Does this include the messages the blocked user will send in chatrooms where blocker and blockee are both members?

I think it's only for the one-to-one chats (also because it's harder to implement for the chatrooms)

**Comment by Damrod** [comment]
> Thanks, good point.
> 
> I vote for 2:
> 
> * silently not delivering the sent messages from the blocked to the blocker without actually removing access to the one-to-one chat page
> 
> > Does this include the messages the blocked user will send in chatrooms where blocker and blockee are both members?
> 
> I think it's only for the one-to-one chats (also because it's harder to implement for the chatrooms)

I'm afraid we can't skip this. If you carefully read the scale (that I won't quote here), you can see this is a must. We need blocked users have their messages hidden from the blocking user even in chatrooms.
