### ISSUE TITLE
⚛️ Create a subscribed chat page

### ISSUE THREAD

**Issue by gbudau** [42AGV/ft_transcendence#353]
This page lists all the chatrooms where the authenticated user is a member.

The URL is `/chat`, and will replace the current chat page.

The current chat page URL, which list all the chatrooms, becomes  `/chat/discover`

**Comment by Damrod** [comment]
I think in the scope of this ticket we should have, in the `/chat` URL, not only the chatrooms where the auth user is a member, but also all one to one chats of where there is at least one message. Do we agree? For the one to one part, we will have to wait.
