### ISSUE TITLE
Fix user controller endpoints

### ISSUE THREAD

**Issue by gbudau** [42AGV/ft_transcendence#357]
[`/api/v1/users/me`](http://localhost:3000/api#/users/UserController_getCurrentUser)
[`/api/v1/users/{userName}`](http://localhost:3000/api#/users/UserController_getUserByUserName)

These two endpoints may conflict if a user has `me` as their username.

How to reproduce:

Create an user with `me` username
Logout and login with a different user
Go to http://localhost:3000/user/me
It displays the authenticated user profile instead of the `me` user profile.

**Comment by Damrod** [comment]
We could forbid 'me' as a user name as a solution

**Comment by gbudau** [comment]
Alternatively, we could do something like the [Github API](https://docs.github.com/en/rest/users/users):

In the controller, if the route is for the authenticated user, it has the [`/user`](https://docs.github.com/en/rest/users/users#get-the-authenticated-user) prefix (singular)

And if it's about other users, it has the [`/users`](https://docs.github.com/en/rest/users/users#get-a-user) prefix (plural)

For example:

`GET /user` -> Get the authenticated user
`GET /users/{username}` Get the user with the username

Currently, in the `UserController`, we add the `/users` prefix by default, but we could remove the prefix and add one of the prefixes to each route.
