### ISSUE TITLE
Make friends page first

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#426]
- Right now we land in the general "users" page. Since we have a friends page, I think is more valuable for the user to land in the list her friends since those are the players she wants to keep an eye on. The users page should be for searching new friends

- ~Also, we have a bug were add friend toggle button is displayed for "me". But toggling it we get an unprocessable entity response and, hence, do nothing.~ (this is duplicated from #396)

**Comment by Damrod** [comment]
There is already a ticket for the second point [here](https://github.com/42AGV/ft_transcendence/issues/396)

**Comment by vdedios** [comment]
Thanks I didn't notice! I'll add it to the PR
