### ISSUE TITLE
White screen in play page

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#562]
Some times we get a white screen in play page, there aren't x steps to reproduced, just play around.

## References:

![image](https://user-images.githubusercontent.com/57688116/221241713-148f9123-a8eb-41ad-a861-2428e9f37c6c.png)

https://github.com/42AGV/ft_transcendence/blob/6c5367c8833491d872ddf4633a9efd14985d2e74/webapp/src/pages/PlayPage/PlayPage.tsx#L49

**Comment by gbudau** [comment]
I'm reopening this issue because the last PR didn't fix all instances where this occurs.
