### ISSUE TITLE
⚛️ Create row UI component

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#62]

**Comment by gbudau** [comment]
This component could have the following props:

- avatar: Avatar component (optional)
- title: Text component (optional)
- subtitle: Text component (optional)
- icon: Icon component (optional)

An example could be something like:

```tsx
<Row avatar={avatar} title='username' subtitle='description' icon={icon} />
```

**Comment by Damrod** [comment]
some minor adjustment to row component
