### ISSUE TITLE
⚛️ Create rows list UI component

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#63]

**Comment by gbudau** [comment]
This component could have the following props:

- rows: array of Rows components

An example could be something like:

```tsx
<RowsList rows={rows} />
```

**Comment by Damrod** [comment]
> This component could have the following props:
> 
> * rows: array of Rows components
> 
> An example could be something like:
> 
> ```tsx
> <RowsList rows={rows} />
> ```

We want this to take an array of RowProps that we internally manage and convert into rows or literally something like JSX.Element[]
```
const Rows : JSX.Element[] = [<Row
    iconVariant={IconVariant.ARROW_FORWARD}
    avatarProps={{ url: randomAvatar, status: 'online' }}
    onClick={btn_action}
    title="John Doe"
    subtitle="level 3"
  />, <Row
    iconVariant={IconVariant.ARROW_FORWARD}
    avatarProps={{ url: randomAvatar, status: 'offline' }}
    onClick={btn_action}
    title="Jane Doe"
    subtitle="level 99"
  /> ];
```
?


The first one fits more the description of this ticket, but the second one doesn't provide stront type checking.

**Comment by gbudau** [comment]
I'd say it is probably better to pass an array of `RowProps`, as you are suggesting.
